//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika05
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bron_num_hotel
    {
        public int id_bronirovania { get; set; }
        public string client { get; set; }
        public string id_hotel_num { get; set; }
        public string data_bron { get; set; }
        public string date_poselenia { get; set; }
        public string date_viezda { get; set; }
    }
}
