//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika05
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id_clients { get; set; }
        public string FIO { get; set; }
        public string Pol { get; set; }
        public string Data_rojdenia { get; set; }
        public string Seria_pasporta { get; set; }
        public string Number_pasprota { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Status_klienta { get; set; }
    }
}
