//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika05
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inf_listok
    {
        public int id_inf_listka { get; set; }
        public string clients { get; set; }
        public string date_polychenia { get; set; }
        public string date_okonchania_deistvia { get; set; }
        public string num_dogovora { get; set; }
        public string id_hotel_num { get; set; }
        public string stoimost_yslyg { get; set; }
        public string hotel_num { get; set; }
    }
}
